services:
  #for local development we don't need the image directly.Uncomment if you want to use the image you built and choose local as env
  kitchenai_{{cookiecutter.project_name}}:
    image: kitchenai_{{cookiecutter.project_name}}
    ports:
    - "8000:8000"
    network_mode: host
    environment:
      - OPENAI_API_KEY
    env_file:
      - .env
